### ISSUE TITLE
delete_dataset_by_name sometimes fails

### ISSUE THREAD

**Issue by bencaine1** [verilylifesciences/analysis-py-utils#18]
delete_dataset_by_name sometimes fails with an error like this:

`google.api_core.exceptions.NotFound: 404 GET https://www.googleapis.com/bigquery/v2/projects/packard-campbell-processed/datasets/bcaine_infirmary_unified_bp_20180420_updated_facility/tables?pageToken=qc_invalid_values_input: Not found: Token qc_invalid_values_input`

I believe it has to do with the fact that it's deleting objects while iterating through related objects.

**Comment by laurendukes** [comment]
Release 0.3.0 upgraded the BigQuery library so it should now be possible to pass this option in through an API call instead of iterating through the tables like we do currently.

**Comment by bencaine1** [comment]
Fixed by https://github.com/verilylifesciences/analysis-py-utils/commit/12295d3e4cbf3d7fa308b2e66b42527061e76b7d
