### ISSUE TITLE
Before 6/18: Switch over imports from google-cloud-* to product-specific imports

### ISSUE THREAD

**Issue by bencaine1** [verilylifesciences/analysis-py-utils#19]
From https://pypi.org/project/google-cloud/

WARNING: The google-cloud Python package is deprecated. On June 18, 2018, this package will no longer install any other packages. Please install the product-specific google-cloud-* packages needed for your application.

I'm not sure if there are any google-cloud imports we need other than bigquery, but in that case we can just remove the google-cloud import.

**Comment by laurendukes** [comment]
Fixed in release 0.3.0.
