### ISSUE TITLE
upgrade google-cloud when the stable branch includes google-cloud-bigquery 0.29.0

### ISSUE THREAD

**Issue by laurendukes** [verilylifesciences/analysis-py-utils#4]
Recently I did the work to upgrade from google-cloud-bigquery 0.26.0 to 0.29.0, not realizing that the most recent stable release of google-cloud used google-cloud-bigquery 0.28.0. Right now I'm just going to update the google-cloud-bigquery library and leave a TODO to change the google-cloud version when the stable release includes 0.29.0.

**Comment by bencaine1** [comment]
Looks like google-cloud is going away in favor of product-specific imports (e.g. google-cloud-bigquery), see https://github.com/verilylifesciences/analysis-py-utils/issues/19. You can probably close this issue.

**Comment by laurendukes** [comment]
Fixed in release 0.3.0.
