### ISSUE TITLE
Request for a copy_table method

### ISSUE THREAD

**Issue by laurendukes** [verilylifesciences/analysis-py-utils#5]
It would be good to have a method to copy a table from one dataset to another within the same project.

**Comment by sheran786malik** [comment]
use the data adapter to fill the data. The way to do it would be: public int Fill (StartingNo, MaxNo, DataSet, 
NameOfTable)

**Comment by laurendukes** [comment]
Thanks for the idea! Fortunately BigQuery 0.29 has a function for this built in to the python API. I'm in the process of upgrading to that version.

**Comment by laurendukes** [comment]
Added as of commit 5ebb05caceed95004a8f0e3194883d9cdff0f2bf
